name: msc
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10.8
  
  # Core dependencies
  - pandas=1.5.3
  - numpy=1.23.5
  - requests=2.28.2
  - tqdm=4.65.0
  
  # TIMM via pip
  - pip
  - pip:
    - timm==0.9.12
  
  # Deep Learning - PyTorch
  - pytorch=2.0.1
  - torchvision=0.15.2
  #- pytorch-cuda=11.8  # Use pytorch-cuda=11.7 or cpuonly if no GPU
  
  # Image processing
  - pillow=9.5.0
  - opencv=4.7.0
  
  # Data visualization
  - matplotlib=3.7.1
  - seaborn=0.12.2
  
  # Scientific computing
  - scikit-learn=1.2.2
